CREATE TABLE reservations (
  id UUID NOT NULL PRIMARY KEY,
  user_id UUID NOT NULL,
  travel_id UUID NOT NULL,
  seat_id UUID NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

