CREATE TABLE travels (
  id UUID NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  destination VARCHAR(255) NOT NULL,
  price NUMERIC(7,2) NOT NULL,
  departure TIMESTAMP(3) NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE seat_status as ENUM ('FREE', 'PROCESSING', 'RESERVED');

CREATE TABLE seats (
  id UUID NOT NULL PRIMARY KEY,
  travel_id UUID NOT NULL REFERENCES travels(id),
  position INTEGER NOT NULL,
  status seat_status NOT NULL DEFAULT 'FREE',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
